src/Entity/Commande.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\UuidInterface;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Symfony\Component\Validator\Mapping\ClassMetadata;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\CommandeRepository")
 */
class Commande
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $NbBillet;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $PrixTotal;

    /**
     * The internal primary key.
     * @var UuidInterface
     *
     * @ORM\Column(type="uuid", unique=true)
     */
    private $NumeroCommande;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Email
     */
    private $email;

    /**
     * @ORM\Column(type="boolean")
     */
    private $formule;

    /**
    * @ORM\OneToMany(targetEntity="App\Entity\Billet",mappedBy="billetCommande", cascade={"persist","remove"})
    */
    private $billets;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank
     */
    private $DateCommande;

    /**
     * @Assert\Callback
     */
    public function validate(ExecutionContextInterface $context, $payload)
    {
        if ($this->getformule() && date('G') >= 14 && $this->getDateCommande()->diff(new \DateTime())->d==0) {
            dump($this->getDateCommande()->diff(new \DateTime())->d==0);
            $context->buildViolation('Vous ne pouvez pas réserver un billet journée après 14h pour le jour même.')
                ->atPath('DateCommande')
                ->addViolation();
        }
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbBillet(): ?int
    {
        return $this->NbBillet;
    }

    public function setNbBillet(int $NbBillet): self
    {
        $this->NbBillet = $NbBillet;

        return $this;
    }

    public function getPrixTotal(): ?int
    {
        return $this->PrixTotal;
    }

    public function setPrixTotal(int $PrixTotal): self
    {
        $this->PrixTotal = $PrixTotal;

        return $this;
    }

    public function getNumeroCommande(): UuidInterface
    {
        return $this->NumeroCommande;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->DateCommande;
    }

    public function setDateCommande(\DateTimeInterface $DateCommande): self
    {
        $this->DateCommande = $DateCommande;

        return $this;
    }

    public function getBillets()
    {
        return $this->billets;
    }

    public function addBillet(Billet $billet): self
    {
        if (!$this->billets->contains($billet)) {
            $this->billets[] = $billet;
            $billet->setBilletCommande($this);
        }

        return $this;
    }

    public function removeBillet(Billet $billet): self
    {
        if ($this->billets->contains($billet)) {
            $this->billets->removeElement($billet);
            // set the owning side to null (unless already changed)
            if ($billet->getBilletCommande() === $this) {
                $billet->setBilletCommande(null);
            }
        }

        return $this;
    }

    /**
     * Set formule
     *
     * @param string $formule
     *
     * @return Commande
     */
    public function setFormule($formule)
    {
        $this->formule = $formule;

        return $this;
    }

    /**
     * Get formule
     *
     * @return boolean
     */
    public function getformule()
    {
        return $this->formule;
    }


    public function __construct() {



        $this->billets = new ArrayCollection();
        $this->NumeroCommande=Uuid::uuid4();
    }

//    /**
//     * @return ArrayCollection
//     */
//    public function addBillet(Billet $billet)
//    {
//        $this->billets[]=$billet;
//        return $this;
//    }
//
//    /**
//     * @param ArrayCollection $billets
//     */
//    public function removeBillet(Billet $billet)
//    {
//        $this->billets->removeElement($billet);
//    }
}

src/Form/BilletType.php
<?php

namespace App\Form;

use App\Entity\Billet;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilder;
use App\Entity\Commande;
use App\Form\CommandeType;

class BilletType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom', TextType::class, array(
                'required' => true,
                'constraints' => [new Length(['max' => 15])]
            ))
            ->add('prenom', TextType::class, array(
                'required' => true,
                'constraints' => [new Length(['max' => 15])]
            ))
            ->add('dateNaissance', DateType::class, array(
                'label' => 'Date de naissance (JJ/MM/AAAA)',
                'required' => true,
                'widget' => 'single_text',
                'format' => 'dd/MM/yyyy',
                'html5' => false,))
            ->add('pays', CountryType::class, [
                'label' => 'Pays',
                'required' => true,
                'placeholder' => 'Choisir un pays',
            ])

            ->add('reduction', ChoiceType::class, array(
                'label' => 'Tarif Réduit ',
                'choices' => array(
                    'Tarif Normal' => false,
                    'Tarif Etudiant/Militaire' => true,),
            ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Billet::class,
        ]);
    }
}

src/Form/CommandeType.php
<?php

namespace App\Form;

use App\Entity\Commande;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Form\FormBuilder;
use App\Entity\Billet;
use App\Form\BilletType;


class CommandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        for ($i = 1; $i < 12; $i++) {
            $NbBillets[] = $i;
        }
        $builder
            ->add('DateCommande', DateType::class, array(
                'label' => 'Date de la visite',
                'required' => true,
                'widget' => 'single_text',
                'attr' => ['class' => 'js-datepicker'],
                'html5' => false,
            ))
            ->add('Formule', ChoiceType::class, array(
                'label' => 'Type du billet',
                'choices' => array(
                    'Journée' => false,
                    'Demi-Journée' => true,),
            ))
            ->add('NbBillet', ChoiceType::class, array(
                'label' => 'Nombre de billets',
                'required' => true,
                'choices' => $NbBillets
            ))

            ->add('email', EmailType::class, array(
                'required' => true,
            ));

        $builder
            ->add('billets', CollectionType::class, array(
                'label' => 'Suivant',
                'entry_type' => BilletType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,

            ))
            ->add('valider',SubmitType::class, array(
                'attr'=>array(
                    'class'=>'btn btn-primary')
            ));

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Commande::class,
        ]);
    }
}

templates/form/FormBillets.html.twig
{% extends 'base.html.twig' %}


{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock %}

{% block body %}


    <h1 class="display-3 text-center">{{ title }}</h1>

    <div class="container">
        <div class="row">
            <div class="col-8">
                <section class="billetterie">


                    {{ form_start(formBillet) }}

                    <div class="name">
                        {{ form_row(formBillet.nom) }}
                        {{ form_row(formBillet.prenom) }}
                    </div>

                    <div class="calendar">
                        {{ form_row(formBillet.dateNaissance) }}
                        <i>Format: YYYY-MM-JJ</i>
                    </div>

                    <div class="pays">
                        {{ form_row(formBillet.pays) }}
                    </div>

                    <div class="reduced_price">
                        {{ form_row(formBillet.reduction) }}
                        <i>Pour toutes réductions, il faudra présenter une pièce justificative à l'entrée du musée.</i>
                    </div>


                    {{ form_end(formBillet) }}
                </section>
                <br><br><br>
            </div>

        </div>
    </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <script>

            flatpickr(".js-datepicker", {});

    </script>
{% endblock %}

templates/form/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %} Contact{% endblock %}
    
{% block body %}
</br>
<div class="container container1">
	<h1 class="text-center">Contact</h1>
	<hr>
	<div class="row">
	<hr>
		<div class="col-md-4 text-center text-md-left">
		<h1><a href="mailto:le.musee.du.louvre.75@gmail.com?subject=1er contact"><i class="fas fa-envelope"></i></a></h1>
			<h3>Par mail !</h3></br>
				<p>Envoyez-nous un e-mail </br>
				Nous vous répondrons dans </br>
				un délai d'un jour ouvré</p>
		</div>
	<hr>
		<div class="col-md-4 text-center text-md-left">
		<h1><span class="fas fa-wheelchair"></span></h1>
			<h3>Personnes handicapées</h3>
				<p>Standard : +33 (0)1 40 20 50 50 </br>
					Information : +33 (0)1 40 20 53 17 </br>
					Ligne visiteurs handicapés :</br> +33 (0)1 40 20 59 90 
					</br>
					handicap@louvre.fr</p>
		</div>
	<hr>
		<div class="col-md-4 text-center text-md-left">
		<h1><span class="fas fa-phone-square"></span></h1>
			<h3>Par téléphone !</h3>
				<p>Téléphone : + 33 (0)1 40 20 50 50 </br>
				De 9h à 17h pendant l'ouverture du Musée.</p>
		</div>
	<hr>
		<div class="col-md-4 text-center text-md-left">
		<h1><a  href="https://www.facebook.com/" ><i class="fab fa-facebook-square"></i></a></h1>
			<h3>Facebook </h3>
				<p>Suivez nous sur facebook.</p>
		</div>
	<hr>	
		<div class="col-md-4 text-center text-md-left">
		<h1><a  href="https://twitter.com//" ><i class="fab fa-twitter-square"></i></a></h1>
			<h3>twitter </h3>
				<p>Suivez nous sur twitter.</p>
		</div>
	<hr>
		<div class="col-md-4 text-center text-md-left">
		<h1><a  href="https://www.instagram.com/?hl=fr" ><i class="fab fa-instagram"></i></a></h1>
			<h3>instagram </h3>
				<p>Suivez nous sur instagram.</p>
		</div>


	<hr>
	</div>
	<footer>
	  	<p class="text-center"> Musée du Louvre © 2019.</p>
	</footer>

</div>
{% endblock %}

templates/form/home.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="jumbotron">

  <center><h1 class="display-3">{{ title }}</h1>
  <p class="lead">Achetez vos billets en ligne</p>
  <a href="{{path('form')}}"><button type="button" class="btn btn-primary">Billetterie</button></a></center>
  <hr class="my-4">

  <center><img src="{{ asset ('img/bg2.jpg')}}" ></center>
</div>

    <footer class="blue bg-primary pt-4">


        <!-- Footer Links -->

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3 text-secondary">© 2019 Copyright - AMRANI Aghaad
        </div>
        <!-- Copyright -->

    </footer>
{% endblock %}

templates/form/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ title }}
{% endblock %}

{% form_theme formCommande 'bootstrap_4_layout.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/dark.css">
{% endblock %}

{% block body %}


    <h1 class="display-3 text-center">{{ title }}</h1>

    <div class="container">
        <div class="row">
            <div class="col-8">
                <section class="billetterie">


                    {{ form_start(formCommande) }}

                    <div class="calendar">
                        {{ form_row(formCommande.DateCommande) }}
                        <p class="reste text-success">Il reste <span id="Nbbillets"></span> billets pour ce jour.</p>
                        <p class="bloque text-danger">Désolé, il ne reste plus assez de billets pour ce jour.</p>
                    </div>

                    <div class="formule">
                        {{ form_row(formCommande.Formule) }}
                        <i>La formule Demi-journée vous permet de rentrer dans le musée à partir de 14h.</i>
                    </div>

                    <ul class="billet"
                        data-prototype="{{ form_widget(formCommande.billets.vars.prototype)|e('html_attr') }}">
                        <li>{{ form_row(formCommande.NbBillet) }}</li>
                    </ul>

                    <div class="email">
                        {{ form_row(formCommande.email) }}
                    </div>


                    {{ form_end(formCommande) }}
                </section>
                <br><br><br>
            </div>

            <div class="col-4">

            </div>
        </div>
    </div>

  <center><img src="{{ asset ('img/bg2.jpg')}}" ></center>
</div>

    <footer class="blue bg-primary pt-4">


        <!-- Footer Links -->

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3 text-secondary">© 2019 Copyright - AMRANI Aghaad
        </div>
        <!-- Copyright -->

    </footer>
{% endblock %}

    {% block javascripts %}
        {{ parent() }}
        <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

        <script>
            var $collectionHolder;

            $("p.bloque").hide();
            $("p.reste").hide();
            var pickr = flatpickr(".js-datepicker", {
                "disable": ["2019-05-01", "2019-11-01","2019-12-25",
                    function (date,) {
                        // return true to disable
                        return (date.getDay() === 2 || date.getDay() === 0);
                    }
                ],
                "locale": {
                    "firstDayOfWeek": 1 // start week on Monday
                },
               // defaultDate: "today",
                dateFormat: "Y-m-d",
                defaultTime:"now",
                minDate: "today",
                onChange: function (selectedDates, dateStr) {
                    $.get("/limitCommande/" + dateStr, function (data, status) {
                        console.log(data, status);

                        if (data.quantity > 3) {
                            $('#commande_valider').prop('disabled', true);
                            $("p.bloque").show();
                            $("p.reste").hide();

                        } else {
                            $('#commande_valider').prop('disabled', false);
                            $('#Nbbillets').text(1000 - data.quantity);
                            $("p.reste").show();
                            $("p.bloque").hide();
                        }
                    })
                }
            });


            $(document).ready(function () {
                $('#commande_NbBillet').on('change', function (e) {
                    e.preventDefault();
                    $('li.deleteOnChangeForm').remove();
                    // Get the ul that holds the collection of etapes
                    $collectionHolder = $('ul.billet');

                    // count the current form inputs we have (e.g. 2), use that as the new
                    // index when inserting a new item (e.g. 2)
                    $collectionHolder.data('index', $collectionHolder.find(':input').length);

                    var NbBillet = $('#commande_NbBillet').val() - 1;
                    console.log(NbBillet);
                    for (var i = 0; i < NbBillet; i++) {
                        addBilletForm($collectionHolder);
                    }
                });

                function addBilletForm($collectionHolder) {
                    var prototype = $collectionHolder.data('prototype');
                    var index = $collectionHolder.data('index');
                    var newForm = prototype;
                    newForm = newForm.replace(/__name__/g, index);
                    $collectionHolder.data('index', index + 1);
                    var $newFormLi = $('<li class="deleteOnChangeForm"></li>').append(newForm);
                    $('ul.billet').append($newFormLi);
                };

            });
        </script>
    {% endblock %}

templates/form/infos.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ "wordInformation"|trans}}{% endblock %}
    
{% block body %}
</br>
<div class="container container1">
	</br>
	<h1 class="text-center">{{ "wordInformation"|trans}}</h1>
	<hr>

		<div class="container">
			<h4>{{ "openingTime"|trans}}</h4>
			</br>
			<p> {{ "monday"|trans}} : 9h - 18h <br/>
				{{ "tuesday"|trans}} : Fermé <br/>
				{{ "wednesday"|trans}} : 9h - 21h45 <br/>
				{{ "thursday"|trans}} : 9h - 18h <br/>
				{{ "friday"|trans}} : 9h -21h45 <br/>
				{{ "saturday"|trans}} : 9h - 18h <br/>
				{{ "sunday"|trans}} : 9h - 18h </p>

			<p>{{ "closing"|trans}}</p>

			<p>{{ "daysOff"|trans}}</p>

			<hr>

			<h4>{{ "prices"|trans}}</h4>
			</br>
			<p> {{ "kids"|trans}} : {{ "free"|trans}} <br/>
			{{ "kids2"|trans}} : 8€ <br/>
			{{ "adults"|trans}} : 16€ <br/>
			{{ "seniors"|trans}} : 12€ </p>
			<p> {{ "halfday"|trans}} : {{"halfprice"|trans}}.<p>
			<p> {{ "reducedPrice"|trans}} : 10€ ({{ "who"|trans}},...) {{ "justificated"|trans}}.</p>

			<hr>

			<h4>{{ "acces"|trans}}</h4>
			</br>
			<p> En métro : lignes 1 et 7, station "Palais-Royal / Musée du Louvre" </p>

			<p> En bus : bus n° 21, 24, 27, 39, 48, 68, 69, 72, 81, 95 </p>

			<p>{{ "velib"|trans}}<br/>
			n°1015 : 2 place A. Malraux	<br/>
			n°1023 : 165 rue Saint-Honoré	<br/>
			n°1014 : 5 rue de l’Echelle	<br/>
			n°1013 : 186 rue Saint-Honoré </p>

			<p> {{ "car"|trans}} : {{ "carPark"|trans}}. </p>

			<p> En Batobus : Escale Louvre, quai François Mitterrand </p>
		</div>
	<hr>

	<footer>
	  	<p class="text-center"> Musée du Louvre © 2019.</p>
	</footer> <br/>

</div>
{% endblock %}

templates/form/recap.html.twig
{% extends 'base.html.twig' %}

{% block body %}


    <h1 class="display-3 text-center">BILLETTERIE</h1>

    <div class="container">
        <div class="row">
            <div class="col-12">

            <div class="card-header">Récapitulatif des billets</div>
            <div class="card-body">
            <table class="table table-dark table-striped">
                <thead>
                <tr>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Pays</th>
                    <th>Prix (en €)</th>
                </tr>
                </thead>
                <tbody>
                {% for billet in commande.billets %}
                    <tr>
                    <td>{{ billet.nom }}</td>
                    <td>{{ billet.prenom }}</td>
                    <td>{{ billet.pays }}</td>
                    <td>{{ billet.prix }}</td>
                    </tr>{% endfor %}
                </tbody>
            </table>
            <div class="card-header">Récapitulatif de la commande</div>
            <div class="card-body">
            <table class="table table-dark table-striped">
                <thead>
                <tr>
                    <th>Nombre de billet(s)</th>
                    <th>Adresse email</th>
                    <th>Prix Total(en €)</th>
                </tr>
                </thead>

                <tbody>
                <tr>
                    <td>{{ commande.NbBillet -1}}</td>
                    <td>{{ commande.email }}</td>
                    <td id="total">{{ commande.prixTotal }}</td>
                </tr>
                </tbody>
            </table>

            <form action="{{ path('success', { 'id': commande.id }) }}" method="POST">
                <script
                        src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                        data-key="pk_test_cWkOARNfUI51IZrJc2bgorRk00uaXJdhlP"
                        data-amount="{{ commande.prixTotal *100 }}"
                        data-name="Stripe.com"
                        data-description="Example charge"
                        data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
                        data-locale="auto"
                        data-zip-code="true">
                </script>
            </form>
            <br><br><br>
        </div>

    </div>
{% endblock %}

templates/form/success.html.twig
{% extends 'base.html.twig' %}

{% block body %}


    <h1 class="display-3 text-center">BILLETTERIE</h1>

    <div class="container">
        <div class="row">
            <div class="col-12">

                <div class="card-header">Commande validée avec succès</div>
                <div class="card-body"><p> Merci pour votre commande. Si vous avez un tarif réduit, il est obligatoire de présenter votre carte étudiant, militaire ou équivalent lors de l'entrée. </p>


                </div>
            </div>
        </div>
    </div>
{% endblock %}